const r = require("express").Router();
const c = require("../controllers/cart.controller");
const { protect } = require("../middleware/auth");
r.use(protect);
r.get("/", c.get);
r.post("/add", c.add);
r.put("/", c.update);
r.delete("/clear", c.clear);
r.delete("/:productId", c.remove);
module.exports = r;
